CREATE TABLE staging_employees (
    "Employee ID" INTEGER,
    "First Name" TEXT,
    "Age" INTEGER,
    "Gender" TEXT,
    "Years at Company" INTEGER,
    "Job Role" TEXT,
    "Monthly Income" NUMERIC(10,2),
    "Work Life Balance" TEXT,
    "Job Satisfaction" TEXT,
    "Performance Rating" TEXT,
    "Number of Promotions" INTEGER,
    "Overtime" TEXT,
    "Distance from Home" INTEGER,
    "Education Level" TEXT,
    "Marital Status" TEXT,
    "Number of Dependents" INTEGER,
    "Job Level" TEXT,
    "Company Size" TEXT,
    "Company Tenure" INTEGER,
    "Remote Work" TEXT,
    "Leadership Opportunities" TEXT,
    "Innovation Opportunities" TEXT,
    "Company Reputation" TEXT,
    "Employee Recognition" TEXT,
    "Attrition" TEXT
);